#!/usr/bin/env python3

# Hyperparameters and configuration settings
DISTANCE_THRESHOLD_ENABLED = True
DISTANCE_THRESHOLD = 2
DISTANCE_THRESHOLDS = [2.0, 3.0, 4.0, 4.95]
LEARNING_RATES = [0.01]
HIDDEN_SIZES = [256]
BATCH_SIZES = [128]
NUM_EPOCHS = 200
NUM_LAYERS_LIST = [2]
CLASSIFICATION_THRESHOLDS = [0.5]
PATIENCE = 10
PLOT_DPI = 200
