#!/usr/bin/env python3

# Hyperparameters and configuration settings
DISTANCE_THRESHOLD = 2
LEARNING_RATES = [0.01]
HIDDEN_SIZES = [256]
BATCH_SIZES = [128]
NUM_EPOCHS = 200
NUM_LAYERS_LIST = [2]
CLASSIFICATION_THRESHOLDS = [0.5]
REGRESSION_WEIGHT = 1.0
CLASSIFICATION_WEIGHT = 1.0
PATIENCE = 10
